In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning tools
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("GirlGamers.csv")

# Preview data
df.head()

    created_utc  score  ...                             url distinguished
0  1.349266e+09   2700  ...          http://imgur.com/zft7C           NaN
1  1.373409e+09   1127  ...        http://imgur.com/RzYd4Eu           NaN
2  1.361042e+09    745  ...  http://i.imgur.com/ial9J6m.jpg           NaN
3  1.360289e+09    722  ...  http://i.imgur.com/9GOFU96.png           NaN
4  1.372271e+09    723  ...  http://i.imgur.com/AAHhEKY.png           NaN

[5 rows x 22 columns]

In [3]:
# Dataset information
df.info()

# Summary statistics
df.describe()

# Check for missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   created_utc             1000 non-null   float64
 1   score                   1000 non-null   int64
 2   domain                  1000 non-null   str
 3   id                      1000 non-null   str
 4   title                   1000 non-null   str
 5   author                  970 non-null    str
 6   ups                     1000 non-null   int64
 7   downs                   1000 non-null   int64
 8   num_comments            1000 non-null   int64
 9   permalink               1000 non-null   str
 10  selftext                204 non-null    str
 11  link_flair_text         1 non-null      str
 12  over_18                 1000 non-null   bool
 13  thumbnail               1000 non-null   str
 14  subreddit_id            1000 non-null   str
 15  edited                  1000 non-null   str
 16  link_flair_css_class    0 non-null      float64
 17  author_flair_css_class  575 non-null    str
 18  is_self                 1000 non-null   bool
 19  name                    1000 non-null   str
 20  url                     1000 non-null   str
 21  distinguished           14 non-null     str
dtypes: bool(2), float64(2), int64(4), str(14)
memory usage: 709.8 KB

created_utc                  0
score                        0
domain                       0
id                           0
title                        0
author                      30
ups                          0
downs                        0
num_comments                 0
permalink                    0
selftext                   796
link_flair_text            999
over_18                      0
thumbnail                    0
subreddit_id                 0
edited                       0
link_flair_css_class      1000
author_flair_css_class     425
is_self                      0
name                         0
url                          0
distinguished              986
dtype: int64

In [4]:
# Convert categorical columns to numeric
df_encoded = pd.get_dummies(df, drop_first=True)

df_encoded.head()

    created_utc  ...  url_https://www.youtube.com/watch?v=vIkjPwxOcdk
0  1.349266e+09  ...                                            False
1  1.373409e+09  ...                                            False
2  1.361042e+09  ...                                            False
3  1.360289e+09  ...                                            False
4  1.372271e+09  ...                                            False

[5 rows x 6866 columns]

In [6]:
df_encoded.columns

Index(['created_utc', 'score', 'ups', 'downs', 'num_comments', 'over_18',
       'link_flair_css_class', 'is_self', 'domain_24.media.tumblr.com',
       'domain_25.media.tumblr.com',
       ...
       'url_https://twitter.com/miss_raej/status/322097859778457600',
       'url_https://twitter.com/search?q=%231reasonwhy&amp;src=hash',
       'url_https://vgresearcher.wordpress.com/2013/02/08/reactions-to-a-womans-voice-in-an-fps-game-kuznekoff-rose-in-press/',
       'url_https://www.edx.org/courses/MITx/6.00x/2012_Fall/about',
       'url_https://www.facebook.com/colleenforsenate',
       'url_https://www.facebook.com/photo.php?fbid=479216175501374',
       'url_https://www.humblebundle.com/',
       'url_https://www.strongspace.com/postfarm/public/postfarm/uploads-2.0/t/tumblr_m58flrzj251qkwdtzo1_1280.jpg',
       'url_https://www.youtube.com/watch?v=PpHJWOJundY',
       'url_https://www.youtube.com/watch?v=vIkjPwxOcdk'],
      dtype='str', length=6866)

In [9]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [12]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [16]:
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [21]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [23]:
print(rf_model)

RandomForestClassifier(random_state=42)